version: '3'
services:
  db:
    image: mysql:5.7.8
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env.development

  web:
    build: .
    command: /bin/sh -c "bundle exec rails server -e production -p 8888"
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
    env_file:
      - .env.development
    depends_on:
      - db
    restart: always

  elasticsearch:
    build:
      context: ./config/elasticsearch
      dockerfile: Dockerfile
    environment:
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPwd123"
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/backups:/usr/share/elasticsearch/backups
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    expose:
      - "9200"
      - "9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./data/kibana/log:/var/log:rw
    links:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.0
    volumes:
      - ./config/logstash/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch

volumes:
  db-data:
    